### PR TITLE
Updated Intro, Analyze API, Article API, and Discussion API docs.

### PR DESCRIPTION
**Pull request by Swader**
Updates done:
- typo fixes
- missing fields and params added
- PHP syntax highlight added into config
- PHP code examples
- new Intro sub-section (tutorials)
- up-to-date sample return payloads
- converted HTML to MD wherever possible, for ease of editing later on
- logo fixed
- headings and inline links fixed and applied to new docs context
- made text a little more language-agnostic to accommodate for clarity in code samples in various code languages / packages / libraries in the code area
- etc...

### CODE REVIEW

**Comment by Swader** [comment]
I have made some further updates to the docs. Aside from having gone over most of the content and added in code samples, I have also done the following significant change.

All the include files are now in the "includes_erb" folder, and have an additional extension ".erb". They are also explicitly called as Ruby partials in the `index.md.erb` file (now also with updated extension). This was done to allow for sub-partials, something Slate doesn't support out of the box.

With this change, we can now abstract all the common content even further, making sure we only need to change it in one place, should some significant updates happen. Examples include: optional fields common to multiple APIs (querystring, meta, links, breadcrumb), required arguments, parts of POSTing instructions, etc.

The change is merged into my previous PR, along with all the other content updates. For rollback purposes, I've kept the old includes there. I'll submit a delete PR later on, if you agree to the changes in the current one.

**Comment by druwynings** [comment]
Sorry, just now saw this addition. 
I just came across [these files](https://gist.github.com/druwynings/0ebe00df4255641d0f76), which should make life a lot easier to support abstracting out all the common content.

**Comment by druwynings** [comment]
This is looking _really_ good by the way, @Swader

**Comment by Swader** [comment]
Thanks :) Made a new PR #2  with the most recent changes.
Those files are awesome, would have loved to have them sooner. I'll add them into the mix asap.

**Pull request merged**
